version: '3.8'

services:
  app:
    build: .
    container_name: file_upload_app
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/fileupload
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - ./uploads:/usr/src/app/uploads
    command: ["node", "server.js"]

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

